# Generated by Django 2.1.2 on 2018-10-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('EMP_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('EMPLOYEE_NAME', models.CharField(blank=True, max_length=20)),
                ('SALARY', models.IntegerField()),
                ('DEPARTMENT', models.TextField(max_length=200)),
                ('DOB', models.DateField()),
                ('DOJ', models.DateField()),
            ],
        ),
    ]
