# Generated by Django 2.1.2 on 2018-10-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='DEPARTMENT',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='EMPLOYEE_NAME',
            field=models.CharField(max_length=20),
        ),
    ]
